modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/AquexTheSeal/SpartanAwakens/issues"
displayURL=""
license="All Rights Reserved."

[[mods]]
modId="spartanawakens"
version="${file.jarVersion}"
displayName="Spartan Awakens"
authors="Aqu, Blackout"
description='''Spartan Weaponry compatibility for Chaos Awakens.'''
itemIcon="minecraft:diamond_sword"

[[dependencies.spartanawakens]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.spartanawakens]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17]"
ordering="NONE"
side="BOTH"

[[dependencies.spartanawakens]]
modId="chaosawakens"
mandatory=true
versionRange="[0.9,)"
ordering="NONE"
side="BOTH"

[[dependencies.spartanawakens]]
modId="geckolib3"
mandatory=true
versionRange="[3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.spartanawakens]]
modId="spartanweaponry"
mandatory=true
versionRange="[2.1.0,)"
ordering="AFTER"
side="BOTH"
