modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/AquexTheSeal/SpartanAwakens/issues"
displayURL=""
license="All Rights Reserved."

[[mods]]
modId="spartanawakens"
version="1.0.0 for CA 10.0.0.0+"
displayName="Spartan Awakens"
authors="AquexTheSeal, T4One"
description='''Spartan Weaponry compatibility for Chaos Awakens.'''
logoFile="logo.png"

[[dependencies.spartanawakens]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.spartanawakens]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17]"
ordering="NONE"
side="BOTH"

[[dependencies.spartanawakens]]
modId="chaosawakens"
mandatory=true
versionRange="[0.9.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.spartanawakens]]
modId="geckolib3"
mandatory=true
versionRange="[3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.spartanawakens]]
modId="spartanweaponry"
mandatory=true
versionRange="[2.2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.spartanawakens]]
modId="projecte"
mandatory=false
versionRange="[PE1.0,]"
ordering="AFTER"
side="BOTH"
